### PR TITLE
Update events.yml

### PR DESCRIPTION
**Pull request by Cjambor**

### CODE REVIEW

**Comment by kjbrum** [comment]
Is there a reason this got closed without being added?

**Comment by Cjambor** [comment]
That was a mistake on my part. Shiny pretty object click...

Should I resubmit?

CHRIS JAMBOR

**Comment by kjbrum** [comment]
Good to go 👍

**Comment by Cjambor** [comment]
Thanks Kyle!

CHRIS JAMBOR
M.S., Business Analytics 
University of Montana, expected graduation May 2018

C: 310-776-0774
LinkedIn Profile <http://www.linkedin.com/in/chrisjambor>

**Pull request merged**
