### PR TITLE
Added Prairie.Code() as an event

### PR DESCRIPTION
**Pull request by kennethversaw**

### CODE REVIEW

**Comment by kjbrum** [comment]
Could you remove the city from the location and the year from the date?

Just trying to keep things short and concise on the listing page, users can visit the supplied link if they would like to learn more.

Thanks for the contribution.

**Comment by kennethversaw** [comment]
Done

**Comment by kjbrum** [comment]
Shoot you got it done before I could edit my comment.

Could you remove the `group` altogether, I think we will stick with only including the group if it is part of or hosted by a user group.

Thanks!

**Comment by kennethversaw** [comment]
Done again :-).

BTW, Call For Presenters is open, if you know anyone interested.

**Pull request merged**
